// ====================
//  GENERAL ACTIONS (10)
// ====================

export const actions = [
    {
      name: "Attack",
      description: "Make a weapon attack using a melee or ranged weapon.",
      actionCost: "Action",
      type: "MELEE_ATTACK",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "general",
      isBaseAction: true,
      createdAt: Date.now(),
    },
    {
      name: "Dodge",
      description:
        "Focus entirely on avoiding attacks; impose disadvantage on attacks against you until your next turn.",
      actionCost: "Action",
      type: "COMMONLY_AVAILABLE_UTILITY",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "general",
      isBaseAction: true,
      createdAt: Date.now(),
    },
    {
      name: "Dash",
      description:
        "Move up to twice your speed this turn, using your action for movement.",
      actionCost: "Action",
      type: "COMMONLY_AVAILABLE_UTILITY",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "general",
      isBaseAction: true,
      createdAt: Date.now(),
    },
    {
      name: "Disengage",
      description:
        "Your movement doesn’t provoke opportunity attacks for the rest of the turn.",
      actionCost: "Action",
      type: "COMMONLY_AVAILABLE_UTILITY",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "general",
      isBaseAction: true,
      createdAt: Date.now(),
    },
    {
      name: "Hide",
      description:
        "Attempt to conceal yourself from enemies; roll Dexterity (Stealth).",
      actionCost: "Action",
      type: "COMMONLY_AVAILABLE_UTILITY",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "general",
      createdAt: Date.now(),
    },
    {
      name: "Help",
      description:
        "Give an ally advantage on their next ability check or attack roll against a creature within 5 feet.",
      actionCost: "Action",
      type: "COMMONLY_AVAILABLE_UTILITY",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "general",
      createdAt: Date.now(),
    },
    {
      name: "Ready",
      description:
        "Prepare to take an action later when a specified trigger occurs.",
      actionCost: "Action",
      type: "OTHER",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "general",
      createdAt: Date.now(),
    },
    {
      name: "Use an Object",
      description: "Interact with an item such as pulling a lever or drinking a potion.",
      actionCost: "Action",
      type: "OTHER",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "general",
      createdAt: Date.now(),
    },
    {
      name: "Cast a Spell",
      description:
        "Use your action to cast a spell, following its casting time, components, and effects.",
      actionCost: "Action",
      type: "SPELL",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "general",
      createdAt: Date.now(),
    },
    {
      name: "Search",
      description: "Spend your action to look for hidden objects or creatures.",
      actionCost: "Action",
      type: "COMMONLY_AVAILABLE_UTILITY",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "general",
      createdAt: Date.now(),
    },
  
    // ====================
    //  CLASS-SPECIFIC ACTIONS (65)
    // ====================
  
    // ======= Barbarian =======
    {
      name: "Rage",
      description:
        "Enter a furious battle frenzy, gaining bonus damage and resistance.",
      actionCost: "Bonus Action",
      type: "CLASS_FEATURE",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "class_specific",
      requiredClass: "Barbarian",
      targetClass: "Barbarian",
      usesPer: "Long Rest",
      maxUses: 2,
      createdAt: Date.now(),
    },
    {
      name: "Reckless Attack",
      description:
        "Throw caution aside, gaining advantage on melee attacks but granting advantage to enemies that attack you.",
      actionCost: "Action",
      type: "MELEE_ATTACK",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "class_specific",
      requiredClass: "Barbarian",
      targetClass: "Barbarian",
      createdAt: Date.now(),
    },
    {
      name: "Feral Instinct",
      description:
        "Gain advantage on initiative rolls and act normally during surprise rounds.",
      actionCost: "No Action",
      type: "CLASS_FEATURE",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "class_specific",
      requiredClass: "Barbarian",
      targetClass: "Barbarian",
      createdAt: Date.now(),
    },
    {
      name: "Brutal Critical",
      description: "Roll extra damage dice when scoring a melee critical hit.",
      actionCost: "Special",
      type: "CLASS_FEATURE",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "class_specific",
      requiredClass: "Barbarian",
      targetClass: "Barbarian",
      createdAt: Date.now(),
    },
    {
      name: "Relentless Rage",
      description:
        "Stay alive when reduced to 0 HP with a successful Constitution saving throw.",
      actionCost: "Reaction",
      type: "CLASS_FEATURE",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "class_specific",
      requiredClass: "Barbarian",
      targetClass: "Barbarian",
      createdAt: Date.now(),
    },
  
    // ======= Bard =======
    {
      name: "Bardic Inspiration",
      description:
        "Grant an ally a die to add to ability checks, attacks, or saving throws.",
      actionCost: "Bonus Action",
      type: "CLASS_FEATURE",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "class_specific",
      requiredClass: "Bard",
      targetClass: "Bard",
      usesPer: "Long Rest",
      maxUses: "Charisma Modifier",
      createdAt: Date.now(),
    },
    {
      name: "Song of Rest",
      description:
        "Restore extra hit points to allies during a short rest through soothing music.",
      actionCost: "No Action",
      type: "CLASS_FEATURE",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "class_specific",
      requiredClass: "Bard",
      targetClass: "Bard",
      createdAt: Date.now(),
    },
    {
      name: "Countercharm",
      description:
        "Use performance to grant allies advantage on saving throws vs fear or charm.",
      actionCost: "Action",
      type: "SPELL",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "class_specific",
      requiredClass: "Bard",
      targetClass: "Bard",
      createdAt: Date.now(),
    },
    {
      name: "Cutting Words",
      description:
        "Use wit to subtract from a creature's attack roll or ability check.",
      actionCost: "Reaction",
      type: "CLASS_FEATURE",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "class_specific",
      requiredClass: "Bard",
      targetClass: "Bard",
      createdAt: Date.now(),
    },
    {
      name: "Magical Secrets",
      description: "Learn and cast spells from any class list.",
      actionCost: "No Action",
      type: "CLASS_FEATURE",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "class_specific",
      requiredClass: "Bard",
      targetClass: "Bard",
      createdAt: Date.now(),
    },
  
    // ======= Cleric =======
    {
      name: "Channel Divinity",
      description:
        "Channel divine energy to fuel special effects unique to your domain.",
      actionCost: "Action",
      type: "CLASS_FEATURE",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "class_specific",
      requiredClass: "Cleric",
      targetClass: "Cleric",
      usesPer: "Short Rest",
      maxUses: 1,
      createdAt: Date.now(),
    },
    {
      name: "Turn Undead",
      description: "Present your holy symbol to drive away undead.",
      actionCost: "Action",
      type: "SPELL",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "class_specific",
      requiredClass: "Cleric",
      targetClass: "Cleric",
      createdAt: Date.now(),
    },
    {
      name: "Divine Intervention",
      description: "Call upon your deity for miraculous aid.",
      actionCost: "Action",
      type: "CLASS_FEATURE",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "class_specific",
      requiredClass: "Cleric",
      targetClass: "Cleric",
      usesPer: "Day",
      createdAt: Date.now(),
    },
    {
      name: "Spell: Cure Wounds",
      description: "Heal a creature you can touch for 1d8 + Wisdom modifier HP.",
      actionCost: "Action",
      type: "SPELL",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "class_specific",
      requiredClass: "Cleric",
      targetClass: "Cleric",
      spellLevel: 1,
      range: "Touch",
      components: { verbal: true, somatic: true },
      duration: "Instantaneous",
      createdAt: Date.now(),
    },
    {
      name: "Bless",
      description:
        "Up to three creatures gain +1d4 to attack rolls and saving throws.",
      actionCost: "Action",
      type: "SPELL",
      requiresConcentration: true,
      sourceBook: "Player's Handbook",
      category: "class_specific",
      requiredClass: "Cleric",
      targetClass: "Cleric",
      duration: "Concentration, up to 1 minute",
      createdAt: Date.now(),
    },
  
    // ======= Druid =======
    {
      name: "Wild Shape",
      description:
        "Transform into a beast you have seen before for up to several hours.",
      actionCost: "Bonus Action",
      type: "CLASS_FEATURE",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "class_specific",
      requiredClass: "Druid",
      usesPer: "Short Rest",
      maxUses: 2,
      createdAt: Date.now(),
    },
    {
      name: "Produce Flame",
      description:
        "Create a small flame in your hand for light or to hurl as an attack.",
      actionCost: "Action",
      type: "SPELL",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "class_specific",
      requiredClass: "Druid",
      spellLevel: 0,
      createdAt: Date.now(),
    },
    {
      name: "Entangle",
      description:
        "Grasping weeds sprout from the ground, restraining creatures in range.",
      actionCost: "Action",
      type: "SPELL",
      requiresConcentration: true,
      sourceBook: "Player's Handbook",
      category: "class_specific",
      requiredClass: "Druid",
      targetClass: "Druid",
      createdAt: Date.now(),
    },
    {
      name: "Flame Blade",
      description:
        "Conjure a fiery scimitar that deals 3d6 fire damage on hit.",
      actionCost: "Bonus Action",
      type: "SPELL",
      requiresConcentration: true,
      sourceBook: "Player's Handbook",
      category: "class_specific",
      requiredClass: "Druid",
      targetClass: "Druid",
      createdAt: Date.now(),
    },
    {
      name: "Summon Beast",
      description: "Call forth a beast spirit to fight for you.",
      actionCost: "Action",
      type: "SPELL",
      requiresConcentration: true,
      sourceBook: "Tasha’s Cauldron of Everything",
      category: "class_specific",
      requiredClass: "Druid",
      targetClass: "Druid",
      createdAt: Date.now(),
    },// ======= Fighter =======
    {
      name: "Second Wind",
      description:
        "Draw on your stamina to regain hit points equal to 1d10 + your fighter level.",
      actionCost: "Bonus Action",
      type: "CLASS_FEATURE",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "class_specific",
      requiredClass: "Fighter",
      usesPer: "Short Rest",
      maxUses: 1,
      createdAt: Date.now(),
    },
    {
      name: "Action Surge",
      description: "Push yourself beyond your limits to take one additional action.",
      actionCost: "Special",
      type: "CLASS_FEATURE",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "class_specific",
      requiredClass: "Fighter",
      usesPer: "Short Rest",
      maxUses: 1,
      createdAt: Date.now(),
    },
    {
      name: "Indomitable",
      description: "Reroll a failed saving throw.",
      actionCost: "Reaction",
      type: "CLASS_FEATURE",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "class_specific",
      requiredClass: "Fighter",
      usesPer: "Long Rest",
      maxUses: 1,
      createdAt: Date.now(),
    },
    {
      name: "Second Strike",
      description: "Make an additional melee attack as part of an Attack action.",
      actionCost: "Bonus Action",
      type: "MELEE_ATTACK",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "class_specific",
      requiredClass: "Fighter",
      targetClass: "Fighter",
      createdAt: Date.now(),
    },
    {
      name: "Parry",
      description:
        "Reduce incoming melee damage by rolling your superiority die and adding your Dexterity modifier.",
      actionCost: "Reaction",
      type: "CLASS_FEATURE",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "class_specific",
      requiredClass: "Fighter",
      targetClass: "Fighter",
      createdAt: Date.now(),
    },
  
    // ======= Monk =======
    {
      name: "Flurry of Blows",
      description:
        "After taking the Attack action, spend 1 ki to make two unarmed strikes as a bonus action.",
      actionCost: "Bonus Action",
      type: "BONUS_ACTION",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "class_specific",
      requiredClass: "Monk",
      usesPer: "Special",
      createdAt: Date.now(),
    },
    {
      name: "Patient Defense",
      description: "Spend 1 ki point to take the Dodge action as a bonus action.",
      actionCost: "Bonus Action",
      type: "BONUS_ACTION",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "class_specific",
      requiredClass: "Monk",
      targetClass: "Monk",
      createdAt: Date.now(),
    },
    {
      name: "Step of the Wind",
      description:
        "Spend 1 ki to Disengage or Dash as a bonus action, doubling your jump distance.",
      actionCost: "Bonus Action",
      type: "BONUS_ACTION",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "class_specific",
      requiredClass: "Monk",
      targetClass: "Monk",
      createdAt: Date.now(),
    },
    {
      name: "Deflect Missiles",
      description: "Reduce or negate ranged weapon damage from an incoming attack.",
      actionCost: "Reaction",
      type: "REACTION",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "class_specific",
      requiredClass: "Monk",
      targetClass: "Monk",
      createdAt: Date.now(),
    },
    {
      name: "Stunning Strike",
      description: "Spend 1 ki to attempt to stun a creature you hit with a melee weapon attack.",
      actionCost: "No Action",
      type: "CLASS_FEATURE",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "class_specific",
      requiredClass: "Monk",
      targetClass: "Monk",
      createdAt: Date.now(),
    },
  
    // ======= Paladin =======
    {
      name: "Divine Smite",
      description:
        "Expend a spell slot to deal radiant damage on a successful melee attack.",
      actionCost: "No Action",
      type: "CLASS_FEATURE",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "class_specific",
      requiredClass: "Paladin",
      targetClass: "Paladin",
      createdAt: Date.now(),
    },
    {
      name: "Lay on Hands",
      description: "Touch a creature to restore a pool of hit points.",
      actionCost: "Action",
      type: "CLASS_FEATURE",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "class_specific",
      requiredClass: "Paladin",
      usesPer: "Day",
      maxUses: "5 × Paladin Level",
      createdAt: Date.now(),
    },
    {
      name: "Divine Sense",
      description:
        "Know the location of celestial, fiend, or undead within 60 feet.",
      actionCost: "Action",
      type: "CLASS_FEATURE",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "class_specific",
      requiredClass: "Paladin",
      usesPer: "Long Rest",
      maxUses: "1 + Charisma Modifier",
      createdAt: Date.now(),
    },
    {
      name: "Aura of Protection",
      description:
        "Add your Charisma modifier to allies' saving throws within 10 feet.",
      actionCost: "No Action",
      type: "CLASS_FEATURE",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "class_specific",
      requiredClass: "Paladin",
      targetClass: "Paladin",
      createdAt: Date.now(),
    },
    {
      name: "Sacred Weapon",
      description:
        "Channel Divinity to imbue your weapon with divine power, adding your Charisma bonus to attack rolls.",
      actionCost: "Action",
      type: "CLASS_FEATURE",
      requiresConcentration: true,
      sourceBook: "Player's Handbook",
      category: "class_specific",
      requiredClass: "Paladin",
      targetClass: "Paladin",
      createdAt: Date.now(),
    },
  
    // ======= Ranger =======
    {
      name: "Hunter’s Mark",
      description:
        "Mark a creature to deal extra 1d6 damage and track it more easily.",
      actionCost: "Bonus Action",
      type: "SPELL",
      requiresConcentration: true,
      sourceBook: "Player's Handbook",
      category: "class_specific",
      requiredClass: "Ranger",
      targetClass: "Ranger",
      createdAt: Date.now(),
    },
    {
      name: "Favored Foe",
      description:
        "Designate an enemy as your favored target to deal extra damage.",
      actionCost: "Bonus Action",
      type: "CLASS_FEATURE",
      requiresConcentration: true,
      sourceBook: "Tasha’s Cauldron of Everything",
      category: "class_specific",
      requiredClass: "Ranger",
      targetClass: "Ranger",
      createdAt: Date.now(),
    },
    {
      name: "Hide in Plain Sight",
      description:
        "Camouflage yourself, gaining +10 to Stealth while stationary.",
      actionCost: "Action",
      type: "COMMONLY_AVAILABLE_UTILITY",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "class_specific",
      requiredClass: "Ranger",
      targetClass: "Ranger",
      createdAt: Date.now(),
    },
    {
      name: "Volley",
      description: "Make a ranged attack against any number of creatures in an area.",
      actionCost: "Action",
      type: "RANGED_ATTACK",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "class_specific",
      requiredClass: "Ranger",
      targetClass: "Ranger",
      createdAt: Date.now(),
    },
    {
      name: "Evasion",
      description:
        "Take no damage from successful Dexterity saves, half on a failure.",
      actionCost: "Reaction",
      type: "CLASS_FEATURE",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "class_specific",
      requiredClass: "Ranger",
      targetClass: "Ranger",
      createdAt: Date.now(),
    },
  
    // ======= Rogue =======
    {
      name: "Sneak Attack",
      description:
        "Deal extra damage when striking with advantage or when an ally is nearby.",
      actionCost: "No Action",
      type: "CLASS_FEATURE",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "class_specific",
      requiredClass: "Rogue",
      targetClass: "Rogue",
      createdAt: Date.now(),
    },
    {
      name: "Cunning Action",
      description: "Use Dash, Disengage, or Hide as a bonus action.",
      actionCost: "Bonus Action",
      type: "BONUS_ACTION",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "class_specific",
      requiredClass: "Rogue",
      targetClass: "Rogue",
      createdAt: Date.now(),
    },
    {
      name: "Uncanny Dodge",
      description:
        "Use your reaction to halve damage from an attacker you can see.",
      actionCost: "Reaction",
      type: "REACTION",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "class_specific",
      requiredClass: "Rogue",
      targetClass: "Rogue",
      createdAt: Date.now(),
    },
    {
      name: "Evasion",
      description:
        "Avoid damage entirely on successful Dexterity saves against area effects.",
      actionCost: "No Action",
      type: "CLASS_FEATURE",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "class_specific",
      requiredClass: "Rogue",
      targetClass: "Rogue",
      createdAt: Date.now(),
    },
    {
      name: "Reliable Talent",
      description: "Treat any roll of 9 or lower on proficient checks as a 10.",
      actionCost: "No Action",
      type: "CLASS_FEATURE",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "class_specific",
      requiredClass: "Rogue",
      targetClass: "Rogue",
      createdAt: Date.now(),
    },
  
    // ======= Sorcerer =======
    {
      name: "Metamagic: Quickened Spell",
      description:
        "Spend sorcery points to cast a spell that normally takes an action as a bonus action instead.",
      actionCost: "Bonus Action",
      type: "CLASS_FEATURE",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "class_specific",
      requiredClass: "Sorcerer",
      targetClass: "Sorcerer",
      createdAt: Date.now(),
    },
    {
      name: "Metamagic: Twinned Spell",
      description: "Target a second creature with a single-target spell.",
      actionCost: "No Action",
      type: "CLASS_FEATURE",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "class_specific",
      requiredClass: "Sorcerer",
      targetClass: "Sorcerer",
      createdAt: Date.now(),
    },
    {
      name: "Font of Magic",
      description: "Convert spell slots to sorcery points or vice versa.",
      actionCost: "Special",
      type: "CLASS_FEATURE",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "class_specific",
      requiredClass: "Sorcerer",
      targetClass: "Sorcerer",
      createdAt: Date.now(),
    },
    {
      name: "Chaos Bolt",
      description:
        "Unleash a bolt of chaotic energy that changes damage type randomly.",
      actionCost: "Action",
      type: "SPELL",
      requiresConcentration: false,
      sourceBook: "Xanathar’s Guide to Everything",
      category: "class_specific",
      requiredClass: "Sorcerer",
      targetClass: "Sorcerer",
      createdAt: Date.now(),
    },
    {
      name: "Wild Magic Surge",
      description:
        "After casting a spell, roll to trigger a wild magic effect.",
      actionCost: "Special",
      type: "CLASS_FEATURE",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "class_specific",
      requiredClass: "Sorcerer",
      targetClass: "Sorcerer",
      createdAt: Date.now(),
    },
  
    // ======= Warlock =======
    {
      name: "Eldritch Blast",
      description:
        "Fire a beam of crackling energy that deals force damage on a hit.",
      actionCost: "Action",
      type: "SPELL",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "class_specific",
      requiredClass: "Warlock",
      spellLevel: 0,
      createdAt: Date.now(),
    },
    {
      name: "Hex",
      description:
        "Curse a creature to deal extra necrotic damage when you hit it.",
      actionCost: "Bonus Action",
      type: "SPELL",
      requiresConcentration: true,
      sourceBook: "Player's Handbook",
      category: "class_specific",
      requiredClass: "Warlock",
      targetClass: "Warlock",
      createdAt: Date.now(),
    },
    {
      name: "Dark One’s Blessing",
      description:
        "Gain temporary hit points when you reduce a hostile creature to 0 HP.",
      actionCost: "No Action",
      type: "CLASS_FEATURE",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "class_specific",
      requiredClass: "Warlock",
      targetClass: "Warlock",
      createdAt: Date.now(),
    },
    {
      name: "Misty Escape",
      description:
        "When damaged, turn invisible and teleport up to 60 feet.",
      actionCost: "Reaction",
      type: "CLASS_FEATURE",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "class_specific",
      requiredClass: "Warlock",
      targetClass: "Warlock",
      createdAt: Date.now(),
    },
    {
      name: "Pact Weapon Attack",
      description: "Summon and wield your bonded weapon.",
      actionCost: "Action",
      type: "MELEE_ATTACK",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "class_specific",
      requiredClass: "Warlock",
      targetClass: "Warlock",
      createdAt: Date.now(),
    },
  
    // ======= Wizard =======
    {
      name: "Arcane Recovery",
      description:
        "Regain expended spell slots after a short rest up to half your wizard level.",
      actionCost: "No Action",
      type: "CLASS_FEATURE",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "class_specific",
      requiredClass: "Wizard",
      usesPer: "Day",
      createdAt: Date.now(),
    },
    {
      name: "Spell Mastery",
      description: "Cast certain 1st or 2nd‑level spells at will.",
      actionCost: "Special",
      type: "CLASS_FEATURE",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "class_specific",
      requiredClass: "Wizard",
      targetClass: "Wizard",
      createdAt: Date.now(),
    },
    {
      name: "Arcane Ward",
      description:
        "Automatically create a ward that absorbs damage when you cast abjuration spells.",
      actionCost: "No Action",
      type: "CLASS_FEATURE",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "class_specific",
      requiredClass: "Wizard",
      targetClass: "Wizard",
      createdAt: Date.now(),
    },
    {
      name: "Counterspell",
      description: "Interrupt another creature’s spellcasting.",
      actionCost: "Reaction",
      type: "SPELL",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "class_specific",
      requiredClass: "Wizard",
      targetClass: "Wizard",
      createdAt: Date.now(),
    },
    {
      name: "Fireball",
      description:
        "Create an explosion of fire dealing 8d6 fire damage in a 20‑ft radius.",
      actionCost: "Action",
      type: "SPELL",
      requiresConcentration: false,
      sourceBook: "Player's Handbook",
      category: "class_specific",
      requiredClass: "Wizard",
      targetClass: "Wizard",
      createdAt: Date.now(),
    },
  
    // ======= Artificer =======
    {
      name: "Infuse Item",
      description: "Imbue mundane objects with temporary magical properties.",
      actionCost: "Special",
      type: "CLASS_FEATURE",
      requiresConcentration: false,
      sourceBook: "Eberron: Rising from the Last War",
      category: "class_specific",
      requiredClass: "Artificer",
      targetClass: "Artificer",
      createdAt: Date.now(),
    },
    {
      name: "Arcane Jolt",
      description:
        "Channel arcane energy through your weapon or infused strike to restore or damage.",
      actionCost: "No Action",
      type: "CLASS_FEATURE",
      requiresConcentration: false,
      sourceBook: "Tasha’s Cauldron of Everything",
      category: "class_specific",
      requiredClass: "Artificer",
      targetClass: "Artificer",
      createdAt: Date.now(),
    },
    {
      name: "Steel Defender Command",
      description:
        "Command your defender to attack or take another action on your turn.",
      actionCost: "Bonus Action",
      type: "BONUS_ACTION",
      requiresConcentration: false,
      sourceBook: "Eberron: Rising from the Last War",
      category: "class_specific",
      requiredClass: "Artificer",
      targetClass: "Artificer",
      createdAt: Date.now(),
    },
    {
      name: "Spell-Storing Item",
      description: "Store a prepared spell into an infused item for later use.",
      actionCost: "Special",
      type: "CLASS_FEATURE",
      requiresConcentration: false,
      sourceBook: "Tasha’s Cauldron of Everything",
      category: "class_specific",
      requiredClass: "Artificer",
      targetClass: "Artificer",
      createdAt: Date.now(),
    },
    {
      name: "Magic Weapon",
      description:
        "Turn a nonmagical weapon into a +1 magical weapon for up to 1 hour.",
      actionCost: "Bonus Action",
      type: "SPELL",
      requiresConcentration: true,
      sourceBook: "Player's Handbook",
      category: "class_specific",
      requiredClass: "Artificer",
      targetClass: "Artificer",
      createdAt: Date.now(),
    },

    // ====================
    //  MONSTER-SPECIFIC ACTIONS (15)
    // ====================

    // ======= Dragon Actions =======
    {
      name: "Fire Breath",
      description: "The dragon exhales fire in a 15-foot cone. Each creature in that area must make a DC 15 Dexterity saving throw, taking 24 (7d6) fire damage on a failed save, or half as much damage on a successful one.",
      actionCost: "Action",
      type: "SPELL",
      requiresConcentration: false,
      sourceBook: "Monster Manual",
      category: "general",
      createdAt: Date.now(),
    },
    {
      name: "Frightful Presence",
      description: "Each creature of the dragon's choice that is within 120 feet of the dragon and aware of it must succeed on a DC 16 Wisdom saving throw or become frightened for 1 minute.",
      actionCost: "Action",
      type: "SPELL",
      requiresConcentration: false,
      sourceBook: "Monster Manual",
      category: "general",
      createdAt: Date.now(),
    },

    // ======= Undead Actions =======
    {
      name: "Shortsword Attack",
      description: "Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 5 (1d6 + 2) piercing damage.",
      actionCost: "Action",
      type: "MELEE_ATTACK",
      requiresConcentration: false,
      sourceBook: "Monster Manual",
      category: "general",
      attackBonusAbilityScore: "strength",
      isProficient: true,
      damageRolls: [
        {
          dice: { count: 1, type: "D6" },
          modifier: 2,
          damageType: "PIERCING"
        }
      ],
      createdAt: Date.now(),
    },
    {
      name: "Shortbow Attack",
      description: "Ranged Weapon Attack: +4 to hit, range 80/320 ft., one target. Hit: 5 (1d6 + 2) piercing damage.",
      actionCost: "Action",
      type: "RANGED_ATTACK",
      requiresConcentration: false,
      sourceBook: "Monster Manual",
      category: "general",
      attackBonusAbilityScore: "dexterity",
      isProficient: true,
      damageRolls: [
        {
          dice: { count: 1, type: "D6" },
          modifier: 2,
          damageType: "PIERCING"
        }
      ],
      createdAt: Date.now(),
    },

    // ======= Humanoid Actions =======
    {
      name: "Scimitar Attack",
      description: "Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 5 (1d6 + 2) slashing damage.",
      actionCost: "Action",
      type: "MELEE_ATTACK",
      requiresConcentration: false,
      sourceBook: "Monster Manual",
      category: "general",
      attackBonusAbilityScore: "dexterity",
      isProficient: true,
      damageRolls: [
        {
          dice: { count: 1, type: "D6" },
          modifier: 2,
          damageType: "SLASHING"
        }
      ],
      createdAt: Date.now(),
    },
    {
      name: "Greataxe Attack",
      description: "Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 9 (1d12 + 3) slashing damage.",
      actionCost: "Action",
      type: "MELEE_ATTACK",
      requiresConcentration: false,
      sourceBook: "Monster Manual",
      category: "general",
      attackBonusAbilityScore: "strength",
      isProficient: true,
      damageRolls: [
        {
          dice: { count: 1, type: "D12" },
          modifier: 3,
          damageType: "SLASHING"
        }
      ],
      createdAt: Date.now(),
    },
    {
      name: "Javelin Attack",
      description: "Melee or Ranged Weapon Attack: +5 to hit, reach 5 ft. or range 30/120 ft., one target. Hit: 6 (1d6 + 3) piercing damage.",
      actionCost: "Action",
      type: "MELEE_ATTACK",
      requiresConcentration: false,
      sourceBook: "Monster Manual",
      category: "general",
      attackBonusAbilityScore: "strength",
      isProficient: true,
      damageRolls: [
        {
          dice: { count: 1, type: "D6" },
          modifier: 3,
          damageType: "PIERCING"
        }
      ],
      createdAt: Date.now(),
    },

    // ======= Monstrosity Actions =======
    {
      name: "Beak Attack",
      description: "Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 10 (1d10 + 5) piercing damage.",
      actionCost: "Action",
      type: "MELEE_ATTACK",
      requiresConcentration: false,
      sourceBook: "Monster Manual",
      category: "general",
      attackBonusAbilityScore: "strength",
      isProficient: true,
      damageRolls: [
        {
          dice: { count: 1, type: "D10" },
          modifier: 5,
          damageType: "PIERCING"
        }
      ],
      createdAt: Date.now(),
    },

    // ======= Giant Actions =======
    {
      name: "Regeneration",
      description: "The troll regains 10 hit points at the start of its turn. If the troll takes acid or fire damage, this trait doesn't function at the start of the troll's next turn.",
      actionCost: "No Action",
      type: "OTHER",
      requiresConcentration: false,
      sourceBook: "Monster Manual",
      category: "general",
      createdAt: Date.now(),
    },

    // ======= Aberration Actions =======
    {
      name: "Antimagic Cone",
      description: "The beholder's central eye creates a 150-foot cone of antimagic. This works like the antimagic field spell.",
      actionCost: "Action",
      type: "SPELL",
      requiresConcentration: true,
      sourceBook: "Monster Manual",
      category: "general",
      createdAt: Date.now(),
    },
    {
      name: "Eye Ray",
      description: "The beholder shoots one of its eye rays at a random target within 120 feet. Roll a d8 to determine which ray is used.",
      actionCost: "Action",
      type: "SPELL",
      requiresConcentration: false,
      sourceBook: "Monster Manual",
      category: "general",
      createdAt: Date.now(),
    },

    // ======= Additional Monster Actions =======
    {
      name: "Multiattack",
      description: "The monster makes two melee attacks.",
      actionCost: "Action",
      type: "OTHER",
      requiresConcentration: false,
      sourceBook: "Monster Manual",
      category: "general",
      createdAt: Date.now(),
    },
    {
      name: "Bite",
      description: "Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 6 (1d6 + 3) piercing damage.",
      actionCost: "Action",
      type: "MELEE_ATTACK",
      requiresConcentration: false,
      sourceBook: "Monster Manual",
      category: "general",
      attackBonusAbilityScore: "strength",
      isProficient: true,
      damageRolls: [
        {
          dice: { count: 1, type: "D6" },
          modifier: 3,
          damageType: "PIERCING"
        }
      ],
      createdAt: Date.now(),
    },
    {
      name: "Claw",
      description: "Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 4 (1d4 + 2) slashing damage.",
      actionCost: "Action",
      type: "MELEE_ATTACK",
      requiresConcentration: false,
      sourceBook: "Monster Manual",
      category: "general",
      attackBonusAbilityScore: "strength",
      isProficient: true,
      damageRolls: [
        {
          dice: { count: 1, type: "D4" },
          modifier: 2,
          damageType: "SLASHING"
        }
      ],
      createdAt: Date.now(),
    }
  ];