export const items = [
    {
      name: "Traveler’s Rations",
      type: "Adventuring Gear",
      rarity: "Common",
      description: "Basic dried food for long journeys.",
      scope: "global",
      weight: 2,
      cost: 5,
      userId: "user_001",
    },
    {
      name: "Torch",
      type: "Adventuring Gear",
      rarity: "Common",
      description: "Provides bright light in a 20-foot radius.",
      scope: "global",
      weight: 1,
      cost: 1,
      userId: "user_001",
    },
    {
      name: "Leather Armor",
      type: "Armor",
      rarity: "Common",
      description: "Light protection offering modest defense.",
      scope: "global",
      weight: 10,
      cost: 10,
      typeOfArmor: "Light",
      armorClass: 11,
      durability: { current: 15, max: 15, baseDurability: 15 },
      userId: "user_001",
    },
    {
      name: "Short Sword",
      type: "Weapon",
      rarity: "Common",
      description: "A simple blade favored by rogues.",
      scope: "global",
      weight: 2,
      cost: 10,
      damageRolls: [
        {
          dice: { count: 1, type: "D6" },
          modifier: 2,
          damageType: "PIERCING",
        },
      ],
      durability: { current: 25, max: 25, baseDurability: 25 },
      userId: "user_001",
    },
    {
      name: "Wooden Shield",
      type: "Armor",
      rarity: "Common",
      description: "A simple round shield offering +2 AC.",
      scope: "global",
      typeOfArmor: "Shield",
      armorClass: 2,
      durability: { current: 20, max: 20, baseDurability: 20 },
      weight: 6,
      cost: 10,
      userId: "user_002",
    },
    {
      name: "Potion of Healing",
      type: "Potion",
      rarity: "Common",
      description: "Restores small amount of hit points when consumed.",
      scope: "global",
      weight: 0.5,
      effects: "Heals 2d4+2 HP",
      cost: 50,
      userId: "user_002",
    },
    {
      name: "Dagger of Quickness",
      type: "Weapon",
      rarity: "Uncommon",
      description: "A lightweight blade that moves as fast as thought.",
      scope: "entitySpecific",
      weight: 1,
      cost: 500,
      attunement: true,
      damageRolls: [
        {
          dice: { count: 1, type: "D4" },
          modifier: 3,
          damageType: "PIERCING",
        },
      ],
      abilityModifiers: { dexterity: +1 },
      userId: "user_003",
    },
    {
      name: "Ring of Water Breathing",
      type: "Ring",
      rarity: "Uncommon",
      description: "Allows the wearer to breathe underwater indefinitely.",
      scope: "entitySpecific",
      weight: 0,
      cost: 500,
      attunement: true,
      userId: "user_004",
    },
    {
      name: "Cloak of Elvenkind",
      type: "Wondrous Item",
      rarity: "Uncommon",
      description: "Improves stealth and muffles movement.",
      scope: "entitySpecific",
      weight: 2,
      cost: 250,
      attunement: true,
      abilityModifiers: { dexterity: +2 },
      userId: "user_005",
    },
    {
      name: "Scroll of Fire Bolt",
      type: "Scroll",
      rarity: "Common",
      description: "Contains the spell *Fire Bolt*.",
      scope: "global",
      weight: 0.1,
      effects: "Casts Fire Bolt (1d10 FIRE damage)",
      cost: 100,
      userId: "user_006",
    },
    {
      name: "Longbow",
      type: "Weapon",
      rarity: "Uncommon",
      description: "A finely crafted longbow with excellent range.",
      scope: "global",
      weight: 2,
      cost: 50,
      damageRolls: [
        {
          dice: { count: 1, type: "D8" },
          modifier: 2,
          damageType: "PIERCING",
        },
      ],
      durability: { current: 35, max: 35, baseDurability: 35 },
      userId: "user_007",
    },
    {
      name: "Wand of Magic Missiles",
      type: "Wand",
      rarity: "Uncommon",
      description: "Casts *Magic Missile* up to 7 charges per day.",
      scope: "entitySpecific",
      weight: 1,
      cost: 500,
      attunement: true,
      userId: "user_008",
    },
    {
      name: "Boots of Striding and Springing",
      type: "Wondrous Item",
      rarity: "Rare",
      description: "Increases the user's movement and jump distance.",
      scope: "entitySpecific",
      weight: 1,
      cost: 5000,
      attunement: true,
      abilityModifiers: { strength: +1 },
      userId: "user_009",
    },
    {
      name: "Breastplate of the Guardian",
      type: "Armor",
      rarity: "Rare",
      description: "Offers magical resilience and superior protection.",
      scope: "campaignSpecific",
      typeOfArmor: "Medium",
      armorClass: 15,
      weight: 20,
      cost: 400,
      durability: { current: 50, max: 50, baseDurability: 50 },
      attunement: true,
      userId: "user_010",
    },
    {
      name: "Hellfire Dagger",
      type: "Weapon",
      rarity: "Rare",
      description: "Wreathed in eternal flames of the Nine Hells.",
      scope: "entitySpecific",
      weight: 1,
      cost: 5000,
      damageRolls: [
        {
          dice: { count: 1, type: "D4" },
          modifier: 3,
          damageType: "FIRE",
        },
      ],
      attunement: true,
      userId: "user_011",
    },
    {
      name: "Gauntlets of Ogre Power",
      type: "Wondrous Item",
      rarity: "Rare",
      description: "Sets the wearer's Strength to 19.",
      scope: "entitySpecific",
      weight: 2,
      cost: 5000,
      attunement: true,
      abilityModifiers: { strength: +5 },
      userId: "user_012",
    },
    {
      name: "Potion of Invisibility",
      type: "Potion",
      rarity: "Rare",
      description: "Grants invisibility for 1 hour.",
      scope: "entitySpecific",
      weight: 0.5,
      cost: 500,
      attunement: false,
      userId: "user_013",
    },
    {
      name: "Rod of the Python",
      type: "Rod",
      rarity: "Rare",
      description: "Transforms into a giant constrictor snake on command.",
      scope: "campaignSpecific",
      weight: 2,
      cost: 5000,
      attunement: true,
      userId: "user_014",
    },
    {
      name: "Staff of Thunder and Lightning",
      type: "Staff",
      rarity: "Very Rare",
      description: "Crackles with elemental power of storms.",
      scope: "campaignSpecific",
      weight: 4,
      cost: 50000,
      attunement: true,
      damageRolls: [
        { dice: { count: 2, type: "D6" }, modifier: 3, damageType: "LIGHTNING" },
      ],
      userId: "user_015",
    },
    {
      name: "Plate Armor of Radiant Valor",
      type: "Armor",
      rarity: "Very Rare",
      description: "Shines with holy light; grants resistance to necrotic.",
      scope: "campaignSpecific",
      typeOfArmor: "Heavy",
      armorClass: 18,
      weight: 65,
      cost: 50000,
      durability: { current: 100, max: 100, baseDurability: 100 },
      attunement: true,
      userId: "user_016",
    },
    {
      name: "Sword of Life-Stealing",
      type: "Weapon",
      rarity: "Very Rare",
      description:
        "Drains vitality from enemies, healing the wielder slightly.",
      scope: "entitySpecific",
      weight: 3,
      cost: 50000,
      attunement: true,
      damageRolls: [
        { dice: { count: 1, type: "D8" }, modifier: 4, damageType: "NECROTIC" },
      ],
      userId: "user_017",
    },
    {
      name: "Wings of Flying",
      type: "Wondrous Item",
      rarity: "Very Rare",
      description: "Transforms into functional wings when activated.",
      scope: "entitySpecific",
      weight: 0,
      cost: 50000,
      attunement: true,
      userId: "user_018",
    },
    {
      name: "Amulet of the Planes",
      type: "Wondrous Item",
      rarity: "Very Rare",
      description: "Grants teleportation between planes of existence.",
      scope: "campaignSpecific",
      weight: 0,
      cost: 50000,
      attunement: true,
      userId: "user_019",
    },
    {
      name: "Boundarybreaker Ship",
      type: "Vehicle",
      rarity: "Very Rare",
      description: "A magical flying ship capable of planar travel.",
      scope: "campaignSpecific",
      weight: 10000,
      cost: 50000,
      userId: "user_020",
    },
    {
      name: "Tome of Clear Thought",
      type: "Wondrous Item",
      rarity: "Legendary",
      description: "Permanently increases the reader's Intelligence.",
      scope: "entitySpecific",
      weight: 5,
      cost: 500000,
      attunement: false,
      abilityModifiers: { intelligence: +2 },
      userId: "user_021",
    },
    {
      name: "Ring of Three Wishes",
      type: "Ring",
      rarity: "Legendary",
      description: "Contains three charges of the Wish spell.",
      scope: "campaignSpecific",
      weight: 0,
      cost: 500000,
      attunement: true,
      userId: "user_022",
    },
    {
      name: "Holy Avenger",
      type: "Weapon",
      rarity: "Legendary",
      description: "A sacred blade that glows with radiant power.",
      scope: "campaignSpecific",
      weight: 3,
      cost: 500000,
      attunement: true,
      damageRolls: [
        { dice: { count: 2, type: "D10" }, modifier: 5, damageType: "RADIANT" },
      ],
      userId: "user_023",
    },
    {
      name: "Staff of Power",
      type: "Staff",
      rarity: "Legendary",
      description: "A potent focus that enhances spells and defense.",
      scope: "entitySpecific",
      weight: 4,
      cost: 500000,
      attunement: true,
      userId: "user_024",
    },
    {
      name: "Crown of the North Star",
      type: "Wondrous Item",
      rarity: "Legendary",
      description: "Radiates light and enhances spellcasting precision.",
      scope: "entitySpecific",
      weight: 1,
      cost: 500000,
      attunement: true,
      userId: "user_025",
    },
    {
      name: "Dragonbone Greatsword",
      type: "Weapon",
      rarity: "Legendary",
      description: "Forged from ancient dragon remains.",
      scope: "campaignSpecific",
      cost: 500000,
      attunement: true,
      weight: 8,
      damageRolls: [
        { dice: { count: 2, type: "D12" }, modifier: 5, damageType: "SLASHING" },
      ],
      durability: { current: 150, max: 150, baseDurability: 150 },
      userId: "user_026",
    },
    {
      name: "Armor of the Deep Sea",
      type: "Armor",
      rarity: "Legendary",
      description: "Allows survival and combat effectiveness underwater.",
      scope: "campaignSpecific",
      typeOfArmor: "Heavy",
      armorClass: 19,
      weight: 65,
      cost: 500000,
      attunement: true,
      userId: "user_027",
    },
    {
      name: "Rod of Lordly Might",
      type: "Rod",
      rarity: "Legendary",
      description: "Shapeshifts into multiple powerful tools or weapons.",
      scope: "entitySpecific",
      weight: 2,
      cost: 500000,
      attunement: true,
      userId: "user_028",
    },
    {
      name: "Orb of Dragonkind",
      type: "Wondrous Item",
      rarity: "Artifact",
      description: "Calls and commands dragons across the world.",
      scope: "campaignSpecific",
      weight: 1,
      cost: 5000000,
      attunement: true,
      userId: "user_029",
    },
    {
      name: "Blackblade of Despair",
      type: "Weapon",
      rarity: "Artifact",
      description: "Consumes souls and whispers madness to its wielder.",
      scope: "campaignSpecific",
      weight: 3,
      cost: 5000000,
      attunement: true,
      damageRolls: [
        { dice: { count: 3, type: "D10" }, modifier: 6, damageType: "NECROTIC" },
      ],
      userId: "user_030",
    },
    {
      name: "Shield of the Hidden Sun",
      type: "Armor",
      rarity: "Artifact",
      description:
        "A radiant shield that can emit sunlight once per long rest.",
      scope: "campaignSpecific",
      typeOfArmor: "Shield",
      armorClass: 3,
      weight: 6,
      cost: 5000000,
      attunement: true,
      userId: "user_031",
    },
    {
      name: "The Heart of the World Tree",
      type: "Wondrous Item",
      rarity: "Artifact",
      description:
        "A living seed that can restore entire forests or worlds.",
      scope: "campaignSpecific",
      weight: 0.1,
      cost: 5000000,
      attunement: true,
      userId: "user_032",
    },
    {
      name: "Crown of the First Lich",
      type: "Wondrous Item",
      rarity: "Artifact",
      description:
        "Empowers necromantic magic and grants control over the undead.",
      scope: "entitySpecific",
      weight: 1,
      cost: 5000000,
      attunement: true,
      abilityModifiers: { intelligence: +4, wisdom: +2 },
      userId: "user_033",
    },
    {
      name: "Phoenix Feather Cloak",
      type: "Wondrous Item",
      rarity: "Unique",
      description:
        "Allows resurrection once per year from ashes after death.",
      scope: "campaignSpecific",
      weight: 1,
      cost: 10000000,
      attunement: true,
      userId: "user_034",
    },
    {
      name: "Soulforged Armor",
      type: "Armor",
      rarity: "Unique",
      description: "Bound to the user's life force; cannot be removed.",
      scope: "entitySpecific",
      typeOfArmor: "Heavy",
      armorClass: 21,
      weight: 65,
      cost: 10000000,
      durability: { current: 200, max: 200, baseDurability: 200 },
      attunement: true,
      userId: "user_035",
    },
    {
      name: "Eternal Echo Wand",
      type: "Wand",
      rarity: "Unique",
      description: "Amplifies and stores the echo of every spell cast.",
      scope: "entitySpecific",
      weight: 1,
      cost: 10000000,
      attunement: true,
      userId: "user_036",
    },
    {
      name: "Horn of Endless War",
      type: "Wondrous Item",
      rarity: "Unique",
      description:
        "Summons spectral warriors when blown on the battlefield.",
      scope: "campaignSpecific",
      weight: 2,
      cost: 10000000,
      attunement: true,
      userId: "user_037",
    },
    {
      name: "Mirror of True Reflections",
      type: "Wondrous Item",
      rarity: "Unique",
      description:
        "Shows the viewer their true self—physical, mental, and spiritual.",
      scope: "global",
      weight: 10,
      cost: 10000000,
      attunement: false,
      userId: "user_038",
    },
    {
      name: "Specter's Cloak",
      type: "Wondrous Item",
      rarity: "Very Rare",
      description:
        "Allows phasing through solid matter a few times per day.",
      scope: "campaignSpecific",
      weight: 1,
      cost: 50000,
      attunement: true,
      userId: "user_039",
    },
    {
      name: "Bow of the Eclipse",
      type: "Weapon",
      rarity: "Legendary",
      description: "Channels moonlight and shadow into its arrows.",
      scope: "campaignSpecific",
      weight: 2,
      cost: 500000,
      damageRolls: [
        { dice: { count: 2, type: "D8" }, modifier: 4, damageType: "RADIANT" },
      ],
      attunement: true,
      userId: "user_040",
    },
    {
      name: "Pegasus Mount",
      type: "Mount",
      rarity: "Rare",
      description: "A winged horse, loyal and noble.",
      scope: "campaignSpecific",
      weight: 1500,
      cost: 15000,
      userId: "user_041",
    },
    {
      name: "Chariot of Fire",
      type: "Vehicle",
      rarity: "Legendary",
      description:
        "A divine chariot engulfed in harmless flames, traversing skies.",
      scope: "campaignSpecific",
      weight: 500,
      cost: 500000,
      attunement: true,
      userId: "user_042",
    },
    {
      name: "Treasure Chest of Endless Coin",
      type: "Treasure",
      rarity: "Unique",
      description:
        "Produces 10 gold coins a day, but never accumulates wealth.",
      scope: "global",
      weight: 25,
      cost: 10000000,
      attunement: false,
      userId: "user_043",
    },
    {
      name: "Anvil of Creation",
      type: "Tool",
      rarity: "Artifact",
      description:
        "Can forge anything, even magical relics, at divine precision.",
      scope: "campaignSpecific",
      weight: 200,
      cost: 5000000,
      attunement: true,
      userId: "user_044",
    },
    {
      name: "Stone of Dimension Crossing",
      type: "Wondrous Item",
      rarity: "Artifact",
      description:
        "Allows a single traveler to step between worlds unharmed.",
      scope: "campaignSpecific",
      weight: 0.5,
      cost: 5000000,
      attunement: true,
      userId: "user_045",
    },
    {
      name: "Heartstring Bow",
      type: "Weapon",
      rarity: "Rare",
      description:
        "The string hums softly with emotion, reacting to the wielder's resolve.",
      scope: "entitySpecific",
      weight: 2,
      cost: 5000,
      attunement: true,
      userId: "user_046",
    },
    {
      name: "Mask of Whispers",
      type: "Wondrous Item",
      rarity: "Rare",
      description: "Grants telepathic communication within 100 feet.",
      scope: "entitySpecific",
      weight: 0.5,
      cost: 5000,
      attunement: true,
      userId: "user_047",
    },
    {
      name: "Crystal Wand of Frost",
      type: "Wand",
      rarity: "Rare",
      description: "Casts freezing magic, slowing enemies.",
      scope: "entitySpecific",
      weight: 1,
      cost: 5000,
      attunement: true,
      userId: "user_048",
    },
    {
      name: "Ring of Illusions",
      type: "Ring",
      rarity: "Uncommon",
      description: "Allows minor illusions at will.",
      scope: "global",
      weight: 0,
      cost: 500,
      attunement: true,
      userId: "user_049",
    },
    {
      name: "Scroll of Meteor Swarm",
      type: "Scroll",
      rarity: "Legendary",
      description: "Contains the spell *Meteor Swarm*.",
      scope: "campaignSpecific",
      weight: 0.1,
      cost: 500000,
      attunement: false,
      userId: "user_050",
    },
  ];